#:schema node_modules/wrangler/config-schema.json
name = "cogn-unified-mcp-server"
main = "src/index.ts"
compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

[[migrations]]
new_sqlite_classes = ["CognMCP"]
tag = "v1"

[[durable_objects.bindings]]
class_name = "CognMCP"
name = "MCP_OBJECT"

[observability]
enabled = true